### ISSUE TITLE
Help - please forgive my dumb-userness

### ISSUE THREAD

**Issue by repligator** [P2Enjoy/kohya_ss-docker#1]
Firstly, thank you for preparing a Linux based solution (who really does do anything on Windows these days?...).

Secondly, please help. Could you provide more specific instructions on how to setup the docker? For example:

1. Let's say I want to take the easy way out and use pip to install the whl's instead of building them myself. At what point in the process should I do this?
2. Where do I find libnvinfer*7.deb? All my searching seems to indicate that I need to be a member of the NVIDIA developer program in order to download it.

**Comment by St33lMouse** [comment]
I'm glad I'm not the only one who thinks there is absolutely zero information as to how to use this.  If you manage to get the Kohya script running on linux you're already doing better than most, but I have to say I don't even know what a wheel is, except that it goes on a car.

Where exactly does this package go? Why does it need another installation of torch and whatnot when Kohya already has a venv with torch in it? What the Devil are you supposed to do here?

**Comment by repligator** [comment]
I can only hope the dev or a user more experienced then us is able to help.

> but I have to say I don't even know what a wheel is, except that it goes on a car.
["Wheels are a component of the Python ecosystem that helps to make package installs just work...A wheel is a type of built distribution. In this case, built means that the wheel comes in a ready-to-install format and allows you to skip the build stage required with source distributions..."](https://realpython.com/python-wheels/)
From my understanding wheels exist to make processes like this simpler. 

> Where exactly does this package go?
The wheels go in kohya_ss/data . libnvinfer*7.deb (if you can find one, I still haven't been able to) goes in kohya_ss/data/libs . 

> Why does it need another installation of torch and whatnot when Kohya already has a venv with torch in it?
The original Kohya script uses a wheel of xformers that is made for windows. I tried replacing it with the anylinux equivalent but unfortunately it doesn't seem to be that simple.

**Comment by Aeitto** [comment]
Idk, maybe this guy doesn't know how to explain the setup. Because right now this repo is pretty much useless. Nobody in the community is running this. Nor RunPod staff want to make a template.

**Comment by martinobettucci** [comment]
Hello @repligator, @St33lMouse, @Aeitto 

Sorry for the poor quality of the documentation on the repo. 
You're right, the debian packages are for registered NVidia Developers but... you can download them from inside the official docker (https://hub.docker.com/r/nvidia/cuda/tags): spawn a docker with a 11.6-devel `docker pull nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04` then use `apt-get download ${PACKAGES}` to download the files.
You should recover the files from the container to an external storage and copy them here in `data/libs`.

The required libs depends on your hardware and copute capability of your GPU.
For our T4, it is CM7.5 and the list is :
- PACKAGES="libcudnn${CUDNN_MAJOR_VERSION}=${CUDNN_VERSION}-1+cuda${CUDNN_CUDA_VERSION} libcudnn${CUDNN_MAJOR_VERSION}-dev=${CUDNN_VERSION}-1+cuda${CUDNN_CUDA_VERSION} libnvinfer${LIBNVINFER_MAJOR_VERSION}=${LIBNVINFER_VERSION}-1+cuda${LIBNVINFER_CUDA_VERSION} libnvinfer-plugin${LIBNVINFER_MAJOR_VERSION}=${LIBNVINFER_VERSION}-1+cuda${LIBNVINFER_CUDA_VERSION} libnvinfer-dev=${LIBNVINFER_VERSION}-1+cuda${LIBNVINFER_CUDA_VERSION} libnvinfer-plugin-dev=${LIBNVINFER_VERSION}-1+cuda${LIBNVINFER_CUDA_VERSION} ${CUDA_NVRTC}=${CUDA_NVRTC_VERSION} ${CUDA_NVRTC_DEV}=${CUDA_NVRTC_VERSION}";

Where the versions are:
      - LIBNVINFER_VERSION=7.2.2
      - LIBNVINFER_MAJOR_VERSION=7
      - LIBNVINFER_CUDA_VERSION=11.1
      - CUDNN_VERSION=8.1.1.33
      - CUDNN_MAJOR_VERSION=8
      - CUDNN_CUDA_VERSION=11.2
      - CUDA_NVRTC=cuda-nvrtc-11-1
      - CUDA_NVRTC_DEV=cuda-nvrtc-dev-11-1
      - CUDA_NVRTC_VERSION=11.1.105-1
      - COMPUTE=7.5

**Comment by martinobettucci** [comment]
If you don't feel like to compile your own versions (which means no deepspeed, no cutlas) you can grab the default libraries here:

- https://github.com/P2Enjoy/kohya_ss-docker/tree/main/kohya_ss/data
- https://github.com/P2Enjoy/kohya_ss-docker/tree/main/kohya_ss/data/libs

Read the README and you should be able to find and download the wheel and debian packages.
I can't host the files directly: the licence for the wheels and especially the nvidia libraries forbids me to do that and also to provide automatic installation for them, sorry for the inconvenience.

**Comment by repligator** [comment]
The sites you linked under /libs are libnvinfer8, while the documentation on the same page libnvinfer7. Should I use 7 or 8?

**Comment by martinobettucci** [comment]
Hello @repligator, that depends on the version being linked with the TensorRT libraries.
If you use the precompiled wheels, you need to discover which version were used.

Here is a snippet to print to the console:

```python
import tensorflow
from tensorflow.python.compiler.tensorrt import trt_convert as trt
print('tensorflow.__version__')
print(tensorflow.__version__)
print('trt.trt_utils._pywrap_py_utils.get_linked_tensorrt_version()')
print(trt.trt_utils._pywrap_py_utils.get_linked_tensorrt_version())
print('trt.trt_utils._pywrap_py_utils.get_loaded_tensorrt_version()')
print(trt.trt_utils._pywrap_py_utils.get_loaded_tensorrt_version())
import torch
for devid in range(0,torch.cuda.device_count()):
        print('torch.cuda.get_device_name()')
        print(torch.cuda.get_device_name(devid))
```

In my case, that was 7.2.2 which indeed links to the libnvfer7*.deb
