### ISSUE TITLE
Question: Running without using docker hosts for X server

### ISSUE THREAD

**Issue by LEv145** [P2Enjoy/kohya_ss-docker#11]
In readme:
> Remember to allow docker hosts to clients to your X server.
 ```
# Unsecure way to do (I take no responsability if you do this way) !! 
# You should add the exact host but I leave that to you.
xhost +
```
It's not very safe or convenient. I would like to be able to specify paths
For example, now you can specify the path to the config, but you cannot load the config
![изображение](https://user-images.githubusercontent.com/40071054/224753581-1e090539-6d51-4f36-a471-3232b36d17c5.png)

It would be more convenient to use docker without external manipulation:)
It would work on Wayland

**Comment by Kadah** [comment]
You can do 'xhost local:docker' instead to limit exposure to just the docker group. Not ideal, but slightly better.

Gradio doesn't yet have a local file browser control, it will in a future update, I think v4.

**Comment by LEv145** [comment]
> 
I would be glad to be able to use the path without opening the dialog box:)
I don't need to open a dialog, because I know a path to the files

**Comment by LEv145** [comment]
Oh, you've already added that to the new version, thanks!
![изображение](https://user-images.githubusercontent.com/40071054/226034300-2453ba43-0506-47c4-aff1-ffbc8052e25d.png)

**Comment by martinobettucci** [comment]
@Kadah  Nice addition for the readme 'xhost local:docker' I'll take that!
@LEv145 We will updte this repo ithis weekend :)
