### ISSUE TITLE
Cloud Gpu

### ISSUE THREAD

**Issue by sneccc** [P2Enjoy/kohya_ss-docker#14]
Can i run kohya on a linux cloud gpu machine, with no interface appart from jupyter notebook ? it doesnt support the triton ui part where it asks for a file locally

**Comment by martinobettucci** [comment]
It seams to me you are addressing two problems at the same time?
You should be able to run this with cloud GPU (because this is exactly how we do it).
The TRITON should be installed prior the pip requirement, the docker does exactly that.

**Comment by martinobettucci** [comment]
@sneccc here is the official COLAB version for our repository: https://gist.github.com/martinobettucci/545adb371fcc6a72e8a72e66eae482dc
