### ISSUE TITLE
Can you please Provide correct links to the packages you asked use to compile ?

### ISSUE THREAD

**Issue by runner22k** [P2Enjoy/kohya_ss-docker#2]
Hi, I came from your reply on kohya_ss github page. 
Can you please Provide me correct links to the packages you asked use to compile? I can compile and provide whl packages after compiling. if I can get instructions on how to compile and create a whl packages.

**Comment by martinobettucci** [comment]
Hi @runner22k, I've added a dot file with the name of the wheels tested to be fully working and the link to the public resources to download them.
I'm not going to give full guide on how to compile, I suppose the users willing to do that already knows how to compile torch and xformers :-)

**Comment by martinobettucci** [comment]
Have a look here: 
- https://github.com/P2Enjoy/kohya_ss-docker/tree/main/kohya_ss/data and 
- https://github.com/P2Enjoy/kohya_ss-docker/tree/main/kohya_ss/data/libs
