### ISSUE TITLE
libinfer7 moved to a different place

### ISSUE THREAD

**Issue by hrkrx** [P2Enjoy/kohya_ss-docker#20]
the new url is https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/

**Comment by hrkrx** [comment]
Also the specific xformers version wheel is hard to find. I used https://github.com/AbdBarho/stable-diffusion-webui-docker/releases/download/5.0.0/xformers-0.0.17.dev449-cp310-cp310-manylinux2014_x86_64.whl

**Comment by martinobettucci** [comment]
@hrkrx thank you for the new link!! Will update with next push

**Comment by martinobettucci** [comment]
New build script have removed the necessity to import externally built libraries
