### ISSUE TITLE
Rebase https://github.com/P2Enjoy/kohya_ss ?

### ISSUE THREAD

**Issue by dsully** [P2Enjoy/kohya_ss-docker#4]
Your fork of kohya_ss is behind, could you rebase it? Issues are disabled on that repo.

For those of us who know what they're doing, it'd be preferable to use without Docker.

Also, I'm not sure why the original code used `tkinter`, as web browsers provide a file dialog. 

I think removing that and diverging from upstream would be best.

**Comment by runner22k** [comment]
yes. having normal code instead of docker would help a bit

**Comment by martinobettucci** [comment]
Hi @dsully and @runner22k,

the fork might be "outdated" sometimes but it is "a feature" XD
Seriously, the fork WILL ONLY BE UPDATED if the linux build is fully stable.

I've added a description in the homepage of the fork

**Comment by martinobettucci** [comment]
@dsully the image was updated with the latest changes :)

**Comment by dsully** [comment]
Thank you!

**Comment by dsully** [comment]
Probably shouldn't commit the `.idea/` files to your fork BTW.
