### ISSUE TITLE
Launch with Gradio share

### ISSUE THREAD

**Issue by AJAlkaline** [P2Enjoy/kohya_ss-docker#5]
Hey, thanks for making this.

I was able to get it to run but is there any way to set share=True in the launch function? It doesn't appear to be among the args I can set in docker_compose.yaml, as kohya_gui.py doesn't normally accept it.

**Comment by AJAlkaline** [comment]
Ah, I figured out a way, I just had to exec into the container shell and then use vim to edit kohya_gui.py.

**Comment by martinobettucci** [comment]
I will plan to add it when the upstream add it, I'm not making a fork to improve but merely to dockerize the existing container :)
