### ISSUE TITLE
Incompatible versions in requirements

### ISSUE THREAD

**Issue by AngainorDev** [P2Enjoy/kohya_ss-docker#6]
https://github.com/P2Enjoy/kohya_ss/blob/master/requirements.txt
has
deepspeed
triton==2.0.0.dev20230208

but trying to install deepspeed (0.8.1) raises
[WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
[WARNING]  One can disable sparse_attn with DS_BUILD_SPARSE_ATTN=0
[ERROR]  Unable to pre-compile sparse_attn
(compiles ok with `export DS_BUILD_SPARSE_ATTN=0;pip3 install deepspeed`)

Also, on my build, deepspeed didn't build when installed in one go.
I have to install torch first of all, then only can install deepspeed, or deepspeed install complains about missing torch if done from the same requirements.txt

**Comment by martinobettucci** [comment]
Yes, you're right! @AngainorDev 
This has been fixed with last push
