### ISSUE TITLE
Multi GPU use

### ISSUE THREAD

**Issue by AngainorDev** [P2Enjoy/kohya_ss-docker#7]
Hi,

It would seem the GUI script is not ready for multi GPU.
I use a dual 3090 setup.
Running with accelerate starts 2 servers:
```
Load CSS...
Load CSS...
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.
```
Is there a way to use accelerate with the UI, or only with the train_network.py script?
Can you provide some guidance?

**Comment by martinobettucci** [comment]
Hi @AngainorDev,

the configuration is embedded in the project [default_config.yaml](https://github.com/P2Enjoy/kohya_ss-docker/blob/main/data/.cache/huggingface/accelerate/default_config.yaml)

Feel free to change it with your accelerate configuration of yours.
If you don't know how to build a YAML file, please refers to the official guide: https://huggingface.co/docs/accelerate/index
:-)

Please, let me know if that worked out for you!

**Comment by AngainorDev** [comment]
Hi,
I know how to configure accelerate, but the issue lies in the script and calling method.
This is more related to the original script, not your wrapping btw.

I tried several things, that failed:
A- single gpu, using deepspeed with default config, fp16
`TypeError: _forward_unimplemented() got an unexpected keyword argument 'output_hidden_states` when calling `enc_out = text_encoder(input_ids, output_hidden_states=True, return_dict=True)`. 

B- 2 local gpus:
B1 - as it is now, the gui is started 2 times, not only by the main process. The gui has no reason to be started by accelerate, only the training script itself.
B2 - It fails anyway running accelerate just on the training script, since the way the models and optimizer are `.prepare()` does not satisfy the accelerate requirements for fullyshareddataparallel.

So, as it is now, accelerate is of little use since neither deepspeed nor multigpu is working.
From what I understand, the training script was only partially converted t ouse accelerate and is missing stuff.

Did anyone had success with any of these?

**Comment by martinobettucci** [comment]
Hi @AngainorDev,

I'm actually using both deepspeed and accelerate but I have to admit we had to custom compile triton, tensorflow and xformer as well as deepspeed itself.
You can switch off ACCELERATE by changing the value of the ARG ACCELERATE to false

`docker compose --profile kohya up --build --build-arg ACCELERATE=False` and you won't use accelerate in the docker image
